### ISSUE TITLE
Colorize suddenly returning double string

### ISSUE THREAD

**Issue by CLUSTERfoo** [fazibear/colorize#40] opened 2015-04-07 22:18 UTC
This behavior just appeared, I'm really not sure what's happening:

```
[4] pry(#<Beanshed::Logger>)> "foo".red
=> "\e[0;\e[31mfoo\e[0m;49mfoo\e[0m"
```

Will print a proper red string, followd by `;049m` followed by the string again in white.

Any idea?

**Comment by marcinkornek** [comment] 2015-04-15 07:20
I have the same issue. I checked previous version ( `0.7.4`) and this problem doesn't appear there.  It appears only in `0.7.5`

**Comment by fazibear** [comment] 2015-04-15 07:46
I can't duplicate this issue. What ruby version, any other gems are bundled ?

**Comment by marcinkornek** [comment] 2015-04-15 09:01
I think that this issue appers when you run other tasks which use colorize (or maybe something else what colors). I have this problem when I run `rubocop` and similar code-analysing tools in rake task and I tried to add custom summaries with colorization

**Comment by fazibear** [comment] 2015-04-15 11:47
Can you give me sample code, when this bug occurs ?

**Comment by CLUSTERfoo** [comment] 2015-04-16 18:29
Repo is private so I can't share, but I'm not doing anything out of the ordinary. It's a gem that requires colorize as a runtime dependency, and simply `binding.pry; "foo".red` at application entry point will cause the bug... The bug appeared at one point, without update to gem, and changing version does not help... :/ 

When I have time later I'll try to get to the root cause and report back. For now will remove dependency :/

**Comment by marcinkornek** [comment] 2015-04-16 19:00
Repo is also private. I tried to reproduce problem but without success. I don't know the reason of this problem.. I was adding custom coloured output in rake task which uses ex. `rubocop`, `scss-lint` gems - they use another colorization gem `rainbow` - maybe this is the reason?

**Comment by fazibear** [comment] 2015-04-18 15:34
I think I found problem...

```ruby
require 'rainbow'
require 'colorize'

puts Rainbow("this is red").red.to_s.red

# => [31mthis is red[0

**Comment by fazibear** [comment] 2015-04-18 15:36
and this is difference:
```ruby
"\e[31mthis is red\e[0m" # rainbow
"\e[0;31;49mthis is red\e[0m" # colorize
```

**Comment by fazibear** [comment] 2015-04-18 20:32
Fixed in next version. Thank guys!

**Closed** 2015-04-18 21:15 UTC
